### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by developer-arpit** [arpitasth/github-crash-course#1]
I think it looks better if title color look little bit orange.

The style rule could be change like this:

```css
h1{
    color: #efa82e;
}
```
